// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VialambreAppTest1.Data;

#nullable disable

namespace VialambreAppTest1.Migrations
{
    [DbContext(typeof(ViAppContext))]
    partial class ViAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Brief", b =>
                {
                    b.Property<int>("BriefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BriefId"));

                    b.Property<bool>("AgregarNuevoCliente")
                        .HasColumnType("bit");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArchivosCostos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ArchivosCostosExist")
                        .HasColumnType("bit");

                    b.Property<string>("ArchivosDesign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ArchivosDesignExist")
                        .HasColumnType("bit");

                    b.Property<bool>("Artes")
                        .HasColumnType("bit");

                    b.Property<string>("AsesorDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsesorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsesorFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsesorPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AsignadoCostos")
                        .HasColumnType("bit");

                    b.Property<bool>("AsignadoDesign")
                        .HasColumnType("bit");

                    b.Property<bool>("Boceto")
                        .HasColumnType("bit");

                    b.Property<string>("CanalVenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanalVentaInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("ComentariosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consecutivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CosteadorAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Costos")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Design")
                        .HasColumnType("bit");

                    b.Property<string>("DesignerAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpaqueId")
                        .HasColumnType("int");

                    b.Property<string>("EntregarEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntregarEnInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCanalVenta")
                        .HasColumnType("bit");

                    b.Property<bool>("EsCantidadUnica")
                        .HasColumnType("bit");

                    b.Property<bool>("EsEscala")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRecotizacion")
                        .HasColumnType("bit");

                    b.Property<string>("EscalaInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCostosAceptado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDesignAceptado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecotizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRequerida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaAsesorCostos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaAsesorDesign")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaCostos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaDesign")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueRecotizado")
                        .HasColumnType("bit");

                    b.Property<string>("HV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ImageUrlExist")
                        .HasColumnType("bit");

                    b.Property<bool>("ImagenReferencia")
                        .HasColumnType("bit");

                    b.Property<bool?>("Instalacion")
                        .HasColumnType("bit");

                    b.Property<bool>("KeyVisual")
                        .HasColumnType("bit");

                    b.Property<string>("Linea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Logos")
                        .HasColumnType("bit");

                    b.Property<int?>("LugarEntregaId")
                        .HasColumnType("int");

                    b.Property<bool>("ManualMarca")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MuestraFisica")
                        .HasColumnType("bit");

                    b.Property<string>("NewClientDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewClientFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NewEmpaque")
                        .HasColumnType("bit");

                    b.Property<bool>("NewLugarEntrega")
                        .HasColumnType("bit");

                    b.Property<bool>("NewProducto")
                        .HasColumnType("bit");

                    b.Property<bool>("Ninguna")
                        .HasColumnType("bit");

                    b.Property<int?>("PiezaId")
                        .HasColumnType("int");

                    b.Property<bool>("Planos")
                        .HasColumnType("bit");

                    b.Property<int?>("PresupuestoUnidad")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaAsesorCostos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaAsesorDesign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaCostos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaCostosInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaDesign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAsesor")
                        .HasColumnType("int");

                    b.Property<int>("StatusCostos")
                        .HasColumnType("int");

                    b.Property<int>("StatusDesign")
                        .HasColumnType("int");

                    b.Property<string>("TipoCotizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpaqueInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadesInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorTotalCotizado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BriefId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpaqueId");

                    b.HasIndex("LugarEntregaId");

                    b.HasIndex("PiezaId");

                    b.HasIndex("ProductId");

                    b.ToTable("Brief");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Empaque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empaque");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.LugarEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LugarEntrega");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Pieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcabadoInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcabadosyAccesoriosInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Acrilico")
                        .HasColumnType("bit");

                    b.Property<bool>("Alambre")
                        .HasColumnType("bit");

                    b.Property<string>("ArchivoPieza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BriefId")
                        .HasColumnType("int");

                    b.Property<string>("CantidadPiezas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Cargue")
                        .HasColumnType("real");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentariosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consecutivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cromado")
                        .HasColumnType("bit");

                    b.Property<bool>("Formica")
                        .HasColumnType("bit");

                    b.Property<string>("Item1Alto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item1Ancho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item1name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item2Alto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item2Ancho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item2name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item3Alto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item3Ancho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item3name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item4Alto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item4Ancho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item4name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lamina")
                        .HasColumnType("bit");

                    b.Property<bool>("Laminado")
                        .HasColumnType("bit");

                    b.Property<bool>("Madera")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mdf")
                        .HasColumnType("bit");

                    b.Property<bool>("NingunAcabado")
                        .HasColumnType("bit");

                    b.Property<bool>("NingunAccesorio")
                        .HasColumnType("bit");

                    b.Property<bool>("NingunMaterial")
                        .HasColumnType("bit");

                    b.Property<bool>("Niveladores")
                        .HasColumnType("bit");

                    b.Property<int?>("NumeroPieza")
                        .HasColumnType("int");

                    b.Property<string>("PiezaAlto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiezaAncho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiezaFondo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PiezaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Polietileno")
                        .HasColumnType("bit");

                    b.Property<bool>("Pp")
                        .HasColumnType("bit");

                    b.Property<bool>("Ps")
                        .HasColumnType("bit");

                    b.Property<bool?>("Publicidad")
                        .HasColumnType("bit");

                    b.Property<bool>("Refilado")
                        .HasColumnType("bit");

                    b.Property<bool>("Ruedas")
                        .HasColumnType("bit");

                    b.Property<bool>("Termodoblado")
                        .HasColumnType("bit");

                    b.Property<bool>("Termoformado")
                        .HasColumnType("bit");

                    b.Property<string>("Tintas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Troquelado")
                        .HasColumnType("bit");

                    b.Property<bool>("Tubo")
                        .HasColumnType("bit");

                    b.Property<bool>("Zincado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Pieza");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Brief", b =>
                {
                    b.HasOne("VialambreAppTest1.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.HasOne("VialambreAppTest1.Models.Cliente", null)
                        .WithMany("Briefs")
                        .HasForeignKey("ClienteId");

                    b.HasOne("VialambreAppTest1.Models.Empaque", "Empaque")
                        .WithMany("Briefs")
                        .HasForeignKey("EmpaqueId");

                    b.HasOne("VialambreAppTest1.Models.LugarEntrega", "LugarEntrega")
                        .WithMany("Briefs")
                        .HasForeignKey("LugarEntregaId");

                    b.HasOne("VialambreAppTest1.Models.Pieza", "Pieza")
                        .WithMany("Briefs")
                        .HasForeignKey("PiezaId");

                    b.HasOne("VialambreAppTest1.Models.Product", "Product")
                        .WithMany("Briefs")
                        .HasForeignKey("ProductId");

                    b.Navigation("AppUser");

                    b.Navigation("Empaque");

                    b.Navigation("LugarEntrega");

                    b.Navigation("Pieza");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Cliente", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Empaque", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.LugarEntrega", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Pieza", b =>
                {
                    b.Navigation("Briefs");
                });

            modelBuilder.Entity("VialambreAppTest1.Models.Product", b =>
                {
                    b.Navigation("Briefs");
                });
#pragma warning restore 612, 618
        }
    }
}
